logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 830128
    initialize: true
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      initial-size: 50
      max-idle: 50
      min-idle: 5
      max-wait-millis: 10000
      validation-query: SELECT 1    
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8